/**
 * api/_lib/schema.js - Postgres 스키마 DDL
 *
 * Vercel 번들링 문제로 .sql 파일을 fs로 읽지 않고
 * JS 모듈의 문자열로 스키마를 관리한다.
 * 모든 문장은 CREATE TABLE IF NOT EXISTS라 여러 번 실행해도 안전하다.
 */

export const SCHEMA_SQL = `
-- 상품
CREATE TABLE IF NOT EXISTS products (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  original_price INT,
  discounted_price INT,
  price INT NOT NULL,
  discount_rate INT,
  image_url TEXT,
  images JSONB DEFAULT '[]',
  description TEXT,
  specs JSONB DEFAULT '{}',
  tags JSONB DEFAULT '[]',
  stock INT NOT NULL DEFAULT 20,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 사용자
CREATE TABLE IF NOT EXISTS users (
  username TEXT PRIMARY KEY,
  password_hash TEXT NOT NULL,
  email TEXT,
  role TEXT NOT NULL DEFAULT 'USER',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 리뷰 (상품당 사용자 1건 — 중복 작성 시 23505)
CREATE TABLE IF NOT EXISTS reviews (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id INT NOT NULL,
  username TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(product_id, username)
);

-- 위시리스트
CREATE TABLE IF NOT EXISTS wishlists (
  username TEXT,
  product_id INT,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY(username, product_id)
);

-- 장바구니
CREATE TABLE IF NOT EXISTS carts (
  username TEXT,
  product_id INT,
  quantity INT NOT NULL CHECK (quantity > 0),
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY(username, product_id)
);

-- 주문
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PAID',
  total_price INT NOT NULL,
  discount INT NOT NULL DEFAULT 0,
  final_price INT NOT NULL,
  coupon_code TEXT,
  shipping JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 주문 항목
CREATE TABLE IF NOT EXISTS order_items (
  order_id TEXT NOT NULL,
  product_id INT NOT NULL,
  name TEXT NOT NULL,
  price INT NOT NULL,
  quantity INT NOT NULL
);

-- 쿠폰 (코드는 대문자로 저장)
CREATE TABLE IF NOT EXISTS coupons (
  code TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  amount INT NOT NULL,
  min_order INT NOT NULL DEFAULT 0,
  max_discount INT,
  expires_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT true
);
`;

export default SCHEMA_SQL;
