/**
 * api/_lib/schema.js - Postgres 스키마 DDL
 *
 * Vercel 번들링 문제로 .sql 파일을 fs로 읽지 않고
 * JS 모듈의 문자열로 스키마를 관리한다.
 * 모든 문장은 CREATE TABLE IF NOT EXISTS라 여러 번 실행해도 안전하다.
 */

export const SCHEMA_SQL = `
-- 상품
CREATE TABLE IF NOT EXISTS products (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  original_price INT,
  discounted_price INT,
  price INT NOT NULL,
  discount_rate INT,
  image_url TEXT,
  images JSONB DEFAULT '[]',
  description TEXT,
  specs JSONB DEFAULT '{}',
  tags JSONB DEFAULT '[]',
  stock INT NOT NULL DEFAULT 20,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 사용자
CREATE TABLE IF NOT EXISTS users (
  username TEXT PRIMARY KEY,
  password_hash TEXT NOT NULL,
  email TEXT,
  role TEXT NOT NULL DEFAULT 'USER',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 리뷰 (상품당 사용자 1건 — 중복 작성 시 23505)
CREATE TABLE IF NOT EXISTS reviews (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id INT NOT NULL,
  username TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(product_id, username)
);

-- 위시리스트
CREATE TABLE IF NOT EXISTS wishlists (
  username TEXT,
  product_id INT,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY(username, product_id)
);

-- 장바구니
CREATE TABLE IF NOT EXISTS carts (
  username TEXT,
  product_id INT,
  quantity INT NOT NULL CHECK (quantity > 0),
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY(username, product_id)
);

-- 주문
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PAID',
  total_price INT NOT NULL,
  discount INT NOT NULL DEFAULT 0,
  final_price INT NOT NULL,
  coupon_code TEXT,
  shipping JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 주문 항목
CREATE TABLE IF NOT EXISTS order_items (
  order_id TEXT NOT NULL,
  product_id INT NOT NULL,
  name TEXT NOT NULL,
  price INT NOT NULL,
  quantity INT NOT NULL
);

-- 쿠폰 (코드는 대문자로 저장)
CREATE TABLE IF NOT EXISTS coupons (
  code TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  amount INT NOT NULL,
  min_order INT NOT NULL DEFAULT 0,
  max_discount INT,
  expires_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT true
);
`;

/**
 * 신규 기능용 스키마 증분(ADD) — 기존 prod 데이터 비파괴.
 *
 * 모두 ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS 라
 * 이미 마이그레이션된 DB에서 여러 번 실행해도 안전하다.
 * ensureSchema()가 SCHEMA_SQL(기본 DDL) 실행 후 이 문장들을 실행한다.
 *
 * 주문 상태 라이프사이클(코드에서 강제, 스키마 제약 아님):
 *   PAID -> PREPARING -> SHIPPING -> DELIVERED
 *   (CANCELED 는 PAID / PREPARING 에서만 가능)
 *   - SHIPPING 진입 시 order id 해시 기반 결정론적 tracking_number 부여
 *   - DELIVERED / CANCELED 는 종료 상태 (advanceOrderStatus 시 INVALID_TRANSITION)
 */
export const SCHEMA_MIGRATIONS_SQL = `
-- 사용자 아바타 이미지 URL
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- 리뷰 첨부 이미지 (문자열 URL 배열)
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]';

-- 주문: 배송 추적 / 결제 정보
-- status 는 기존 orders DDL 에 TEXT DEFAULT 'PAID' 로 이미 존재하므로 건드리지 않는다.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_key TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS card_last4 TEXT;

-- 결제
CREATE TABLE IF NOT EXISTS payments (
  id TEXT PRIMARY KEY,
  order_id TEXT,
  username TEXT,
  method TEXT NOT NULL,
  card_last4 TEXT,
  amount INT NOT NULL,
  status TEXT NOT NULL,
  fault TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
`;

export default SCHEMA_SQL;
