/**
 * api/_lib/seedData.js - 시드 데이터 (스키마 초기화/리셋 시 입력)
 *
 * Vercel 번들링 문제로 fs 읽기 없이 JS 모듈로 시드 데이터를 관리한다.
 * - 상품 18종: 기존 api/products.js의 PRODUCTS를 그대로 이식하고
 *   상세 설명/스펙/이미지/태그/재고를 보강했다.
 * - 재고 수치는 기존 api/_lib/inventoryStore.js의 고정 테이블과 동일하다.
 *   (의도적: id 3, 8, 18 재고 0 — 품절/재고부족 네거티브 테스트 픽스처)
 * - 사용자 비밀번호는 시드 시점에 scrypt로 해시한다(해시 하드코딩 금지).
 */

// 동일한 unsplash 사진 id로 파라미터만 다른 이미지 3장을 만든다 (새 사진 id 발명 금지)
function buildImages(imageUrl) {
  const base = imageUrl.split('?')[0];
  return [
    imageUrl,
    `${base}?w=800&h=800&fit=crop`,
    `${base}?w=400&h=400&fit=crop&crop=entropy`,
  ];
}

// 상품 시드 (id 1~18 고정 — 입력 후 identity 시퀀스를 max(id)로 setval)
export const SEED_PRODUCTS = [
  // 전자기기
  {
    id: 1,
    name: '프리미엄 무선 블루투스 이어폰 노이즈 캔슬링',
    category: '전자기기',
    originalPrice: 189000,
    discountedPrice: 129000,
    price: 129000,
    discountRate: 32,
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop'),
    description:
      '하이브리드 액티브 노이즈 캔슬링으로 지하철에서도 온전히 음악에 집중할 수 있는 프리미엄 무선 이어폰입니다. 10mm 다이내믹 드라이버가 풍부한 저음과 섬세한 고음을 균형 있게 재생합니다. 한 번 충전으로 이어폰 단독 8시간, 케이스 포함 최대 32시간 사용이 가능해 출퇴근부터 출장까지 든든합니다. IPX4 생활방수를 지원해 가벼운 운동 중 땀이나 빗방울 걱정이 없습니다. 통화 품질을 높여주는 ENC 마이크로 화상회의에서도 또렷한 목소리를 전달합니다.',
    specs: {
      '블루투스 버전': '5.3',
      '재생시간': '단독 8시간 / 케이스 포함 32시간',
      '충전단자': 'USB-C',
      '방수등급': 'IPX4',
      '무게': '이어버드 5.4g (편측)',
      '노이즈 캔슬링': '하이브리드 ANC (최대 -35dB)',
      '마이크': 'ENC 통화 노이즈 저감 6마이크',
      '코덱': 'SBC / AAC',
    },
    tags: ['무선이어폰', '노이즈캔슬링', '블루투스', '방수', '출퇴근템'],
    stock: 15,
    active: true,
  },
  {
    id: 2,
    name: '스마트 워치 헬스 트래커 방수 기능',
    category: '전자기기',
    originalPrice: 299000,
    discountedPrice: 199000,
    price: 199000,
    discountRate: 33,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop'),
    description:
      '심박수·혈중산소·수면 패턴까지 24시간 기록하는 올인원 헬스 트래커 스마트 워치입니다. 1.43인치 AMOLED 디스플레이는 한낮의 야외에서도 선명하게 보입니다. 5ATM 방수를 지원해 수영장에서도 착용한 채 운동량을 측정할 수 있습니다. 120여 종의 운동 모드와 GPS 내장으로 러닝 코스와 페이스를 정확하게 남겨줍니다. 한 번 충전에 최대 14일 사용 가능한 배터리로 충전 스트레스가 없습니다.',
    specs: {
      '디스플레이': '1.43인치 AMOLED (466x466)',
      '방수등급': '5ATM',
      '배터리': '최대 14일 (일반 사용 기준)',
      '센서': '심박 / 혈중산소 / 가속도 / 자이로',
      'GPS': '내장 (GPS/GLONASS/Beidou)',
      '운동 모드': '120종 이상',
      '호환 OS': 'Android 8.0+ / iOS 12.0+',
      '충전 방식': '마그네틱 무선 충전',
    },
    tags: ['스마트워치', '헬스트래커', '방수', 'GPS', '러닝'],
    stock: 8,
    active: true,
  },
  {
    id: 3,
    name: '휴대용 블루투스 스피커 360도 서라운드 사운드',
    category: '전자기기',
    originalPrice: 79000,
    discountedPrice: 59000,
    price: 59000,
    discountRate: 25,
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop'),
    description:
      '어디에 두어도 공간 전체를 채우는 360도 서라운드 사운드 휴대용 스피커입니다. 듀얼 패시브 라디에이터가 크기를 뛰어넘는 깊은 저음을 들려줍니다. IPX6 방수로 캠핑장 갑작스러운 소나기나 욕실 사용도 문제없습니다. 최대 15시간 연속 재생과 스트랩 포함 580g의 가벼운 무게로 나들이 필수템입니다. 두 대를 페어링하면 진짜 스테레오로 즐길 수 있는 TWS 모드도 지원합니다.',
    specs: {
      '블루투스 버전': '5.1',
      '출력': '20W (풀레인지 x2 + 패시브 라디에이터 x2)',
      '재생시간': '최대 15시간',
      '방수등급': 'IPX6',
      '무게': '580g',
      '충전단자': 'USB-C',
      '부가기능': 'TWS 듀얼 페어링 / AUX 입력',
    },
    tags: ['블루투스스피커', '360도사운드', '방수', '캠핑', '휴대용'],
    // 의도적 테스트 시나리오: id 3은 재고 0 (주문 차단 상품과 겹치는 품절 케이스)
    stock: 0,
    active: true,
  },
  {
    id: 4,
    name: '4K 웹캠 자동 초점 내장 마이크',
    category: '전자기기',
    originalPrice: 129000,
    discountedPrice: 89000,
    price: 89000,
    discountRate: 31,
    imageUrl: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&h=400&fit=crop'),
    description:
      '재택근무와 온라인 강의를 위한 4K UHD 웹캠입니다. 위상차 자동 초점(PDAF)이 움직여도 얼굴을 놓치지 않고 또렷하게 잡아줍니다. 듀얼 노이즈 캔슬링 마이크가 키보드 소음을 걸러내 목소리만 깨끗하게 전달합니다. 어두운 방에서도 자동 광보정으로 자연스러운 화면을 만들어줍니다. 별도 드라이버 설치 없이 USB만 꽂으면 바로 사용할 수 있습니다.',
    specs: {
      '해상도': '4K UHD (3840x2160) 30fps',
      '초점 방식': 'PDAF 자동 초점',
      '화각': '90도 광각',
      '마이크': '듀얼 스테레오 노이즈 캔슬링',
      '연결': 'USB-A (USB 2.0/3.0)',
      '호환 OS': 'Windows / macOS / ChromeOS',
      '부가기능': '프라이버시 커버 / 삼각대 마운트',
    },
    tags: ['웹캠', '4K', '화상회의', '재택근무', '스트리밍'],
    stock: 23,
    active: true,
  },
  {
    id: 5,
    name: '태블릿 10.5인치 8GB RAM 128GB 저장공간',
    category: '전자기기',
    originalPrice: 459000,
    discountedPrice: 359000,
    price: 359000,
    discountRate: 22,
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop'),
    description:
      '영상 감상부터 문서 작업까지 하나로 해결하는 10.5인치 태블릿입니다. 2K 해상도 디스플레이와 쿼드 스피커가 몰입감 있는 미디어 경험을 제공합니다. 8GB RAM과 128GB 저장공간으로 여러 앱을 동시에 띄워도 쾌적하고, microSD로 최대 1TB까지 확장할 수 있습니다. 7,700mAh 대용량 배터리는 동영상 연속 재생 12시간을 버팁니다. 스타일러스 펜을 지원해 필기와 스케치 용도로도 훌륭합니다.',
    specs: {
      '디스플레이': '10.5인치 2K (2000x1200) IPS',
      'RAM': '8GB',
      '저장공간': '128GB (microSD 최대 1TB 확장)',
      '배터리': '7,700mAh (영상 재생 12시간)',
      '카메라': '후면 13MP / 전면 8MP',
      '스피커': '쿼드 스피커 (돌비 애트모스)',
      '충전단자': 'USB-C (18W 고속충전)',
      '무게': '465g',
    },
    tags: ['태블릿', '2K디스플레이', '대화면', '스타일러스', '넷플릭스'],
    stock: 5,
    active: true,
  },
  {
    id: 6,
    name: '노트북 스탠드 알루미늄 각도조절',
    category: '전자기기',
    originalPrice: 55000,
    discountedPrice: 39000,
    price: 39000,
    discountRate: 29,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop'),
    description:
      '거북목을 예방하는 항공기급 알루미늄 노트북 스탠드입니다. 6단계 각도 조절과 높이 조절로 시선을 모니터 높이까지 끌어올려 바른 자세를 만들어줍니다. 통풍이 잘 되는 오픈 구조라 노트북 발열을 자연스럽게 배출합니다. 실리콘 패드가 기기를 흠집 없이 단단히 잡아주고, 최대 17인치 노트북까지 안정적으로 지지합니다. 접으면 두께 6cm로 얇아져 가방에 쏙 들어갑니다.',
    specs: {
      '재질': '항공기급 알루미늄 합금',
      '각도 조절': '6단계 (15~45도)',
      '호환 크기': '11~17인치 노트북',
      '최대 하중': '20kg',
      '접이식': '지원 (접었을 때 두께 6cm)',
      '무게': '890g',
      '미끄럼 방지': '실리콘 패드 8개',
    },
    tags: ['노트북스탠드', '알루미늄', '각도조절', '거북목예방', '데스크셋업'],
    stock: 12,
    active: true,
  },

  // 액세서리
  {
    id: 7,
    name: '인체공학 무선 마우스 DPI 조절 가능',
    category: '액세서리',
    originalPrice: 49000,
    discountedPrice: 35000,
    price: 35000,
    discountRate: 29,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop'),
    description:
      '하루 종일 쥐어도 손목이 편안한 인체공학 무선 마우스입니다. 손바닥의 자연스러운 곡선에 맞춘 그립 디자인으로 장시간 작업 피로를 줄여줍니다. 800부터 3200까지 4단계 DPI 조절 버튼으로 정밀 작업과 빠른 커서 이동을 오갈 수 있습니다. 2.4GHz 동글과 블루투스를 모두 지원해 최대 3대 기기를 버튼 하나로 전환합니다. 저소음 클릭 스위치라 도서관이나 사무실에서도 눈치 보이지 않습니다.',
    specs: {
      '연결 방식': '2.4GHz 동글 + 블루투스 5.0 (멀티페어링 3대)',
      'DPI': '800 / 1200 / 1600 / 3200 (4단계)',
      '버튼': '6버튼 (저소음 스위치)',
      '배터리': 'AA 1개 (최대 12개월)',
      '센서': '고정밀 광학 센서',
      '무게': '98g (배터리 제외)',
      '호환 OS': 'Windows / macOS / Linux',
    },
    tags: ['무선마우스', '인체공학', 'DPI조절', '저소음', '사무용'],
    stock: 30,
    active: true,
  },
  {
    id: 8,
    name: '기계식 RGB 게이밍 키보드 청축',
    category: '액세서리',
    originalPrice: 159000,
    discountedPrice: 119000,
    price: 119000,
    discountRate: 25,
    imageUrl: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400&h=400&fit=crop'),
    description:
      '경쾌한 클릭감의 청축 스위치를 탑재한 기계식 RGB 게이밍 키보드입니다. 1,680만 컬러 RGB 백라이트와 19가지 라이팅 이펙트로 나만의 데스크를 연출할 수 있습니다. 전체 키 무한 동시입력(N-Key Rollover)을 지원해 격렬한 게임에서도 입력 누락이 없습니다. 알루미늄 상판과 이중 사출 키캡으로 오래 써도 각인이 지워지지 않습니다. 분리형 USB-C 케이블이라 휴대와 보관이 간편합니다.',
    specs: {
      '스위치': '청축 (클릭 타입, 수명 5천만 회)',
      '배열': '한영 104키 풀배열',
      '백라이트': 'RGB 1,680만 컬러 / 19가지 이펙트',
      '동시입력': '전체 키 무한 동시입력 (NKRO)',
      '키캡': '이중 사출 ABS',
      '케이블': '분리형 USB-C (1.8m)',
      '상판 재질': '알루미늄',
      '폴링레이트': '1000Hz',
    },
    tags: ['기계식키보드', '청축', 'RGB', '게이밍', '풀배열'],
    // 의도적 테스트 시나리오: id 8은 재고 0 (품절 케이스)
    stock: 0,
    active: true,
  },
  {
    id: 9,
    name: 'USB-C 멀티 허브 7in1 맥북 호환',
    category: '액세서리',
    originalPrice: 69000,
    discountedPrice: 49000,
    price: 49000,
    discountRate: 29,
    imageUrl: 'https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=400&h=400&fit=crop'),
    description:
      '포트가 부족한 노트북에 꼭 필요한 7in1 USB-C 멀티 허브입니다. 4K 60Hz HDMI 출력으로 외장 모니터를 선명하게 연결할 수 있습니다. 100W PD 패스스루 충전을 지원해 허브를 꽂은 채로 노트북 고속 충전이 가능합니다. USB 3.0 포트 2개와 SD/microSD 카드 리더로 카메라 작업자에게 특히 유용합니다. 맥북은 물론 USB-C를 지원하는 윈도우 노트북, 아이패드와도 호환됩니다.',
    specs: {
      '포트 구성': 'HDMI / USB 3.0 x2 / USB-C PD / SD / microSD / USB-C 데이터',
      'HDMI 출력': '4K 60Hz',
      'PD 충전': '최대 100W 패스스루',
      'USB 전송속도': '5Gbps (USB 3.0)',
      '카드 리더': 'SD / microSD (UHS-I)',
      '재질': '알루미늄 바디',
      '케이블 길이': '15cm (일체형)',
    },
    tags: ['USB허브', '맥북액세서리', 'HDMI', '멀티포트', '4K출력'],
    stock: 20,
    active: true,
  },
  {
    id: 10,
    name: '고속 무선 충전 패드 15W 퀵차지',
    category: '액세서리',
    originalPrice: 39000,
    discountedPrice: 29000,
    price: 29000,
    discountRate: 26,
    imageUrl: 'https://images.unsplash.com/photo-1633269540827-728aabbb7646?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1633269540827-728aabbb7646?w=400&h=400&fit=crop'),
    description:
      '올려놓기만 하면 충전이 시작되는 15W 고속 무선 충전 패드입니다. Qi 인증을 받아 아이폰과 갤럭시 모두 안전하게 충전할 수 있습니다. 케이스 두께 5mm까지 인식해 케이스를 벗기지 않아도 됩니다. 과열·과전압·이물질 감지 보호 회로가 밤새 충전해도 기기를 지켜줍니다. 은은한 LED 인디케이터는 수면 모드에서 자동으로 어두워져 침실에서도 방해되지 않습니다.',
    specs: {
      '최대 출력': '15W (7.5W/10W 자동 매칭)',
      '충전 규격': 'Qi 인증',
      '케이스 인식': '두께 5mm 이하',
      '보호 회로': '과열 / 과전압 / 이물질(FOD) 감지',
      '입력': 'USB-C (QC 3.0 어댑터 권장)',
      '크기': '지름 100mm / 두께 8mm',
      '동봉품': 'USB-C 케이블 1m (어댑터 별매)',
    },
    tags: ['무선충전기', '15W고속충전', 'Qi인증', '아이폰', '갤럭시'],
    stock: 14,
    active: true,
  },
  {
    id: 11,
    name: '스마트폰 거치대 자석 타입 360도 회전',
    category: '액세서리',
    originalPrice: 25000,
    discountedPrice: 18000,
    price: 18000,
    discountRate: 28,
    imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop'),
    description:
      '강력한 네오디뮴 자석으로 스마트폰을 착 붙이는 자석식 거치대입니다. 볼 조인트 구조로 360도 회전과 상하 각도 조절이 자유로워 세로·가로 어떤 방향도 한 손으로 바꿀 수 있습니다. N52 등급 자석 6개가 최대 500g까지 흔들림 없이 지지합니다. 책상·주방·차량 어디든 3M 접착 베이스로 간단히 설치합니다. 메탈 플레이트 2장이 동봉되어 케이스 안쪽에 넣어 바로 사용할 수 있습니다.',
    specs: {
      '자석': 'N52 네오디뮴 x6',
      '회전': '360도 볼 조인트',
      '최대 하중': '500g',
      '설치 방식': '3M VHB 접착 베이스',
      '호환': '4~7인치 스마트폰',
      '동봉품': '메탈 플레이트 2장 / 여분 접착패드',
      '재질': '알루미늄 + 실리콘 패드',
    },
    tags: ['거치대', '자석거치대', '360도회전', '차량용', '데스크'],
    stock: 25,
    active: true,
  },
  {
    id: 12,
    name: '보조배터리 20000mAh 고속충전 PD 지원',
    category: '액세서리',
    originalPrice: 59000,
    discountedPrice: 42000,
    price: 42000,
    discountRate: 29,
    imageUrl: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop'),
    description:
      '스마트폰을 4번 이상 충전할 수 있는 20000mAh 대용량 보조배터리입니다. 22.5W PD/QC 고속충전으로 30분 만에 스마트폰 배터리를 60%까지 채웁니다. USB-C 입출력과 USB-A 2포트로 3대 기기를 동시에 충전할 수 있습니다. LED 디스플레이가 남은 배터리를 1% 단위로 정확히 보여줍니다. 기내 반입 가능 용량이라 해외여행에도 부담 없이 챙길 수 있습니다.',
    specs: {
      '용량': '20000mAh (74Wh)',
      '최대 출력': '22.5W (PD 3.0 / QC 3.0)',
      '포트': 'USB-C 입출력 x1 / USB-A x2',
      '동시 충전': '최대 3대',
      '잔량 표시': 'LED 디지털 디스플레이 (1% 단위)',
      '재충전 시간': '약 6.5시간 (18W 입력)',
      '무게': '355g',
      '기내 반입': '가능 (100Wh 이하)',
    },
    tags: ['보조배터리', '20000mAh', 'PD고속충전', '대용량', '여행필수품'],
    stock: 9,
    active: true,
  },

  // 생활
  {
    id: 13,
    name: '스테인리스 텀블러 보온보냉 500ml',
    category: '생활',
    originalPrice: 35000,
    discountedPrice: 24000,
    price: 24000,
    discountRate: 31,
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop'),
    description:
      '아침에 담은 얼음이 퇴근까지 살아있는 진공 이중벽 스테인리스 텀블러입니다. 보온 6시간, 보냉 12시간으로 온도를 오래 지켜줍니다. 식품용 SUS304 스테인리스에 무도장 내벽이라 커피 냄새 배임 없이 위생적입니다. 밀폐 슬라이드 뚜껑은 가방 안에서도 새지 않아 출퇴근길에 안심입니다. 차량 컵홀더에 딱 맞는 슬림한 하단 디자인까지 갖췄습니다.',
    specs: {
      '용량': '500ml',
      '보온': '6시간 (70도 이상)',
      '보냉': '12시간 (7도 이하)',
      '재질': 'SUS304 스테인리스 (진공 이중벽)',
      '뚜껑': '밀폐 슬라이드 (분해 세척 가능)',
      '무게': '285g',
      '컵홀더 호환': '하단 지름 7.2cm',
    },
    tags: ['텀블러', '보온보냉', '스테인리스', '밀폐뚜껑', '사무실'],
    stock: 18,
    active: true,
  },
  {
    id: 14,
    name: 'LED 스탠드 조명 무선충전 기능',
    category: '생활',
    originalPrice: 89000,
    discountedPrice: 65000,
    price: 65000,
    discountRate: 27,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop'),
    description:
      '조명과 무선충전을 하나로 합친 2in1 LED 데스크 스탠드입니다. 받침대에 스마트폰을 올리면 10W 무선충전이 자동으로 시작됩니다. 색온도 3단계와 밝기 5단계를 터치 한 번으로 조절해 공부·작업·휴식 모드에 맞출 수 있습니다. 플리커 프리 LED라 장시간 사용해도 눈이 편안합니다. 접이식 관절 구조로 빛의 방향을 자유롭게 조절하고, 사용하지 않을 때는 납작하게 접어둘 수 있습니다.',
    specs: {
      '광원': 'LED 10W (플리커 프리)',
      '색온도': '3단계 (3000K / 4500K / 6000K)',
      '밝기 조절': '5단계 터치 디밍',
      '무선충전': '10W (Qi 호환)',
      '연색지수': 'Ra 90 이상',
      '전원': 'USB-C 어댑터 (동봉)',
      '구조': '2축 접이식 관절',
      '부가기능': '30분/60분 취침 타이머',
    },
    tags: ['LED스탠드', '무선충전', '데스크조명', '플리커프리', '공부'],
    stock: 7,
    active: true,
  },
  {
    id: 15,
    name: '공기청정기 미니 탁상용 저소음',
    category: '생활',
    originalPrice: 129000,
    discountedPrice: 89000,
    price: 89000,
    discountRate: 31,
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop'),
    description:
      '책상 위 한 뼘 공간이면 충분한 미니 탁상용 공기청정기입니다. H13 등급 헤파필터가 0.3μm 초미세먼지를 99.95% 걸러냅니다. 수면 모드 기준 22dB의 저소음 설계로 잠들 때 머리맡에 두어도 조용합니다. 공기질 센서가 오염도를 3색 LED로 표시하고 자동 모드에서 풍량을 알아서 조절합니다. 4평형 공간에 적합해 원룸·침실·사무실 책상에 안성맞춤입니다.',
    specs: {
      '필터': 'H13 헤파필터 (0.3μm 99.95% 제거)',
      '사용 면적': '약 4평 (13㎡)',
      '소음': '22~48dB (수면~터보)',
      '풍량 조절': '4단계 + 자동 모드',
      '공기질 표시': '3색 LED (좋음/보통/나쁨)',
      '소비전력': '최대 8W',
      '필터 교체 주기': '약 6개월',
      '크기': '지름 17cm x 높이 26cm',
    },
    tags: ['공기청정기', '미니', '저소음', '헤파필터', '원룸'],
    stock: 11,
    active: true,
  },
  {
    id: 16,
    name: '가습기 초음파 3L 대용량 LED 무드등',
    category: '생활',
    originalPrice: 69000,
    discountedPrice: 49000,
    price: 49000,
    discountRate: 29,
    imageUrl: 'https://images.unsplash.com/photo-1615486511484-92e172cc4fe0?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1615486511484-92e172cc4fe0?w=400&h=400&fit=crop'),
    description:
      '한 번 물을 채우면 밤새 촉촉함이 이어지는 3L 대용량 초음파 가습기입니다. 시간당 최대 300ml의 풍부한 분무량을 3단계로 조절할 수 있습니다. 7색 LED 무드등이 은은하게 침실 분위기를 만들어주고, 원하는 색으로 고정할 수도 있습니다. 물이 떨어지면 자동으로 전원이 꺼지는 무수위 차단 기능으로 안전합니다. 상부 급수 방식이라 무거운 본체를 뒤집지 않고 주전자로 바로 물을 부으면 됩니다.',
    specs: {
      '용량': '3L',
      '분무량': '최대 300ml/h (3단계)',
      '가습 방식': '초음파식',
      '연속 사용': '최대 12시간',
      '무드등': '7색 LED (색상 고정 가능)',
      '안전 기능': '무수위 자동 전원 차단',
      '급수 방식': '상부 급수',
      '소음': '28dB 이하',
    },
    tags: ['가습기', '대용량', '무드등', '초음파', '침실'],
    stock: 6,
    active: true,
  },
  {
    id: 17,
    name: '전기담요 세탁가능 자동온도조절',
    category: '생활',
    originalPrice: 89000,
    discountedPrice: 59000,
    price: 59000,
    discountRate: 34,
    imageUrl: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=400&h=400&fit=crop'),
    description:
      '겨울밤을 포근하게 데워주는 극세사 전기담요입니다. 9단계 온도 조절과 취침 타이머로 내 몸에 딱 맞는 온도를 유지합니다. 과열 방지 센서가 열선 온도를 실시간 감시해 안심하고 잠들 수 있습니다. 컨트롤러만 분리하면 세탁기에 통째로 돌릴 수 있어 관리가 쉽습니다. 전자파를 최소화한 EMF 저감 설계로 온 가족이 사용하기 좋습니다.',
    specs: {
      '크기': '더블 (180x140cm)',
      '온도 조절': '9단계 자동온도조절',
      '타이머': '1~12시간 자동 꺼짐',
      '재질': '극세사 (마이크로파이버)',
      '세탁': '컨트롤러 분리 후 세탁기 사용 가능',
      '안전 기능': '과열 방지 센서 / EMF 저감 설계',
      '소비전력': '120W',
    },
    tags: ['전기담요', '세탁가능', '온도조절', '겨울침구', '극세사'],
    stock: 13,
    active: true,
  },
  {
    id: 18,
    name: '발마사지기 무선 온열 기능',
    category: '생활',
    originalPrice: 159000,
    discountedPrice: 119000,
    price: 119000,
    discountRate: 25,
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop',
    images: buildImages('https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop'),
    description:
      '하루 종일 서 있던 발의 피로를 풀어주는 무선 온열 발마사지기입니다. 지압 롤러와 에어백이 발바닥부터 발등까지 입체적으로 주무릅니다. 45도 온열 기능이 혈액순환을 도와 마사지 효과를 높여줍니다. 무선 설계라 소파·침대·사무실 어디서든 전원선 없이 사용할 수 있습니다. 3가지 마사지 모드와 3단계 강도로 그날의 피로에 맞게 선택하세요. 발을 대는 커버는 분리 세탁이 가능해 위생적입니다.',
    specs: {
      '마사지 방식': '지압 롤러 + 에어백 압박',
      '온열': '최대 45도',
      '모드': '3가지 모드 / 3단계 강도',
      '배터리': '2500mAh (무선 약 90분 사용)',
      '충전단자': 'USB-C',
      '호환 사이즈': '~290mm (남녀공용)',
      '커버': '분리 세탁 가능',
      '자동 종료': '15분 타이머',
    },
    tags: ['발마사지기', '온열', '무선', '피로회복', '선물추천'],
    // 의도적 테스트 시나리오: id 18은 항상 재고 0 (재고 부족 네거티브 테스트 픽스처)
    stock: 0,
    active: true,
  },
];

// 사용자 시드 — 비밀번호는 시드 시점에 scrypt로 해시한다 (auth-hash.js 사용)
export const SEED_USERS = [
  { username: 'test', password: '1234', email: 'test@example.com', role: 'USER', status: 'ACTIVE' },
  { username: 'admin', password: '1234', email: 'admin@example.com', role: 'ADMIN', status: 'ACTIVE' },
  // 의도적 테스트 시나리오: test2는 차단 계정 (로그인 시 403)
  { username: 'test2', password: '1234', email: 'test2@example.com', role: 'USER', status: 'BLOCKED' },
];

// 리뷰 시드 — 기존 api/reviews.js의 INITIAL_REVIEWS를 그대로 이식
export const SEED_REVIEWS = [
  {
    id: 1,
    productId: 1,
    username: 'test',
    rating: 5,
    comment: '음질이 정말 좋아요! 노이즈 캔슬링도 훌륭합니다.',
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 2,
    productId: 1,
    username: 'user123',
    rating: 4,
    comment: '가격 대비 만족스럽습니다.',
    createdAt: '2024-01-20T14:20:00Z',
  },
  {
    id: 3,
    productId: 2,
    username: 'test',
    rating: 5,
    comment: '운동할 때 정말 유용해요!',
    createdAt: '2024-01-25T09:15:00Z',
  },
];

// 쿠폰 시드 — 코드는 대문자로 저장 (조회는 대소문자 무관)
export const SEED_COUPONS = [
  {
    code: 'WELCOME10',
    type: 'percent',
    amount: 10,
    minOrder: 0,
    maxDiscount: 20000,
    expiresAt: null,
    active: true,
  },
  {
    code: 'SAVE5000',
    type: 'fixed',
    amount: 5000,
    minOrder: 30000,
    maxDiscount: null,
    expiresAt: null,
    active: true,
  },
  {
    code: 'VIP20',
    type: 'percent',
    amount: 20,
    minOrder: 100000,
    maxDiscount: 50000,
    expiresAt: null,
    active: true,
  },
  // 의도적 테스트 시나리오: 만료된 쿠폰 (만료 네거티브 픽스처 — 만료 검증은 핸들러에서)
  {
    code: 'EXPIRED10',
    type: 'percent',
    amount: 10,
    minOrder: 0,
    maxDiscount: null,
    expiresAt: '2024-01-01T00:00:00Z',
    active: true,
  },
];
